// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkST4-eG3qBzTTIebMnT4rDtAXAguFqLA',
    appId: '1:698331459211:web:c9e14008e272ab4ac3ae8e',
    messagingSenderId: '698331459211',
    projectId: 'neocarga-app',
    authDomain: 'neocarga-app.firebaseapp.com',
    storageBucket: 'neocarga-app.firebasestorage.app',
    measurementId: 'G-G64V473J83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnoYcvOMPlGR9ErstqnEF9coTbW8U2_-E',
    appId: '1:698331459211:android:92a38bb58c8d50b0c3ae8e',
    messagingSenderId: '698331459211',
    projectId: 'neocarga-app',
    storageBucket: 'neocarga-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLFz8aluNn609hplk5Mwvli8PEHiNNEs',
    appId: '1:698331459211:ios:4e40c08c01fe1114c3ae8e',
    messagingSenderId: '698331459211',
    projectId: 'neocarga-app',
    storageBucket: 'neocarga-app.firebasestorage.app',
    iosBundleId: 'com.example.neocarga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLFz8aluNn609hplk5Mwvli8PEHiNNEs',
    appId: '1:698331459211:ios:4e40c08c01fe1114c3ae8e',
    messagingSenderId: '698331459211',
    projectId: 'neocarga-app',
    storageBucket: 'neocarga-app.firebasestorage.app',
    iosBundleId: 'com.example.neocarga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkST4-eG3qBzTTIebMnT4rDtAXAguFqLA',
    appId: '1:698331459211:web:71f2725eb2b89493c3ae8e',
    messagingSenderId: '698331459211',
    projectId: 'neocarga-app',
    authDomain: 'neocarga-app.firebaseapp.com',
    storageBucket: 'neocarga-app.firebasestorage.app',
    measurementId: 'G-SCBMVL7JY1',
  );
}
